- name: "bug"
  color: "#d73a4a"
  description: "Что-то не работает"
- name: "documentation"
  color: "#0075ca"
  description: "Улучшения или дополнения документации"
- name: "duplicate"
  color: "#cfd8d7"
  description: "Этот issue или pull request уже существует"
- name: "enhancement"
  color: "#a22eef"
- name: "wontfix_it"
  color: "#000000"
  description: "На это не будет потрачено время"
  from_name: "wontfix"
