name: "КПТ: микро-цель"
description: "Шаблон для фиксации одной короткой рабочей цели перед сессией (Заголовок + краткое описание шагов/критериев)."
body:
  - type: input
    id: title
    attributes:
      label: "Заголовок"
      description: "Коротко — одно действие. Глагол в инфинитиве + объект. Писать 1–2 минуты (пример: \"Определить, что такое OpenAPI-спецификация\")."
      placeholder: "Например: Определить, что такое OpenAPI-спецификация"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Описание"
      description: "Короткие пункты: шаги и критерии готовности (3–5 пунктов). Быстро набросать, не вылизывать текст."
      placeholder: "- Посмотреть, что это такое\n- Понять, для чего используется\n- Прикинуть, как её создавать"
    validations:
      required: false
