name: "CBT: быстрая сессия"
description: "Короткая CBT-сессия: быстрая подготовка, цель и поток мыслей. Заполняется ~1–2 минуты."
title: "CBT: {date} — {goal}"
body:
  - type: markdown
    attributes:
      value: |
        **Быстрая CBT-сессия** — перед началом сделай подготовку: протереть очки, убрать отвлекающие факторы, 1–2 глубоких вдоха.
  - type: dropdown
    id: suds
    attributes:
      label: "SUDS — уровень дискомфорта (0 — спокойно, 10 — максимум)"
      description: "Оцени, насколько напряжён/тревожен ты сейчас (SUDS)."
      options:
        - "0"
        - label: "1"
        - label: "2"
        - label: "3"
        - label: "4"
        - label: "5"
        - label: "6"
        - label: "7"
        - label: "8"
        - label: "9"
        - label: "10"
  - type: dropdown
    id: energy
    attributes:
      label: "Энергия (0–5)"
      description: "Оценка общей энергии/готовности к работе"
      options:
        - label: "0 — нет энергии"
        - label: "1"
        - label: "2"
        - label: "3"
        - label: "4"
        - label: "5 — полон энергии"
  - type: checkboxes
    id: prep_checks
    attributes:
      label: "Быстрая подготовка — отметь, что сделал"
      options:
        - label: "Протёр очки / убрал блики"
        - label: "Проверил рабочее место (чисто, проветрено)"
        - label: "Отключил уведомления"
        - label: "Сделал дыхательное упражнение (1 мин)"
        - label: "Включил необходимые программы"
  - type: input
    id: goal
    attributes:
      label: "Короткая цель сессии (одно предложение) — станет основой для sub-issue"
      description: "Напиши одну фразу — что хочешь сделать за сессию (например: 'Add unit test for login')."
      placeholder: "Коротко: ..."
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "Короткие заметки / мысли перед началом (можно не аккуратно)"
      description: "Пиши простыми словами — как себя чувствуешь, что мешает, короткий план (2–5 пунктов)."
      placeholder: "Открыть VS Code, создать папку ..., написать тест..., и т.д."
