name: "CBT: быстрая сессия"
description: "Короткая CBT-сессия: быстрая подготовка, цель и поток мыслей. Заполняется ~1–2 минуты."
# (не задаём дефолтные labels кроме опционального 'cbt' — если хочешь, создай label вручную в репо)
title: "CBT: {date} — {goal}"
body:
  - type: markdown
    attributes:
      value: |
        **Быстрая CBT-сессия** — перед началом сделай подготовку: протереть очки, убрать отвлекающие факторы, 1–2 глубоких вдоха.
  - type: dropdown
    id: suds
    attributes:
      label: "SUDS — уровень дискомфорта (0 — спокойно, 10 — максимум)"
      description: "Оцени, насколько напряжён/тревожен ты сейчас (SUDS)."
      options:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
  - type: dropdown
    id: energy
    attributes:
      label: "Энергия (0–5)"
      description: "Оценка общей энергии/готовности к работе"
      options:
        - "0 — нет энергии"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5 — полон энергии"
  - type: checkboxes
    id: prep_checks
    attributes:
      label: "Быстрая подготовка — отметь, что сделал"
      options:
        - "Протёр очки / убрал блики"
        - "Проверил рабочее место (чисто, проветрено)"
        - "Отключил уведомления"
        - "Сделал дыхательное упражнение (1 мин)"
        - "Включил необходимые программы"
  - type: input
    id: goal
    attributes:
      label: "Короткая цель сессии (одно предложение) — станет основой для sub-issue"
      description: "Напиши одну фразу — что хочешь сделать за сессию (например: 'Add unit test for login')."
      placeholder: "Коротко: ..."
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "Короткие заметки / мысли перед началом (можно не аккуратно)"
      description: "Пиши простыми словами — как себя чувствуешь, что мешает, короткий план (2–5 пунктов)."
      placeholder: "Открыть VS Code, создать папку ..., написать тест..., и т.д."
